version: '3.8'

services:
  # Tempo OpenTelemetry Collector
  tempo:
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo.yml"
    ports:
      - "3200:3200"  # Tempo HTTP API
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./tempo-config.yml:/etc/tempo.yml
      - tempo-data:/etc/tempo/data
    networks:
      - tempo-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Grafana web interface
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - tempo-network

networks:
  tempo-network:
    driver: bridge

volumes:
  tempo-data:
  grafana-data: