apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      traceQuery:
        search: {}
        # Tempo configuration for trace search
        enabled: true
      maxOutcomes: 500
      serviceMap:
        enabled: true
    secureJsonData: {}
    readOnly: false